apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: payments-lab
  source:
    repoURL: 'https://github.com/SEU_USUARIO/payments-lab.git'   # <-- SUBSTITUA
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
